//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstroCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Aquarius 的本地化字符串。
        /// </summary>
        internal static string Aquarius {
            get {
                return ResourceManager.GetString("Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aries 的本地化字符串。
        /// </summary>
        internal static string Aries {
            get {
                return ResourceManager.GetString("Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancer 的本地化字符串。
        /// </summary>
        internal static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capricorn 的本地化字符串。
        /// </summary>
        internal static string Capricorn {
            get {
                return ResourceManager.GetString("Capricorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gemini 的本地化字符串。
        /// </summary>
        internal static string Gemini {
            get {
                return ResourceManager.GetString("Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leo 的本地化字符串。
        /// </summary>
        internal static string Leo {
            get {
                return ResourceManager.GetString("Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Libra 的本地化字符串。
        /// </summary>
        internal static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pisces 的本地化字符串。
        /// </summary>
        internal static string Pisces {
            get {
                return ResourceManager.GetString("Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sagittarius 的本地化字符串。
        /// </summary>
        internal static string Sagittarius {
            get {
                return ResourceManager.GetString("Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scorpio 的本地化字符串。
        /// </summary>
        internal static string Scorpio {
            get {
                return ResourceManager.GetString("Scorpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuarus 的本地化字符串。
        /// </summary>
        internal static string Taurus {
            get {
                return ResourceManager.GetString("Taurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virgo 的本地化字符串。
        /// </summary>
        internal static string Virgo {
            get {
                return ResourceManager.GetString("Virgo", resourceCulture);
            }
        }
    }
}
